### ISSUE TITLE
Remplacer le service Google favicon ?

### ISSUE THREAD

**Issue by rivetchip** [timovn/local-favicon-cache#1]
Hello,

Pourquoi ne pas remplacer le service Google par un script perso ? En cas de défaut de service, ou si Google venait à disparaître ( ouais je sais, je peux rêver :smile:  ) par exemple.
- faire une requête vers le `le_site/favicon.ico`
- sinon, requête et parser l'`<html><head>`: à la recherche d'un :

```
<link rel="icon [shortcut]" href="xxx" [type="image/xxx"]>
```

et convertir en PNG si besoin en comparant le type-mime / extension
- sinon, afficher une image par défaut

.
Des avis ?

Bye.

**Comment by timovn** [comment]
C’est une idée, mais si j’ai voulu utilise le service de Google, c’est pour sa fiabilité : le service retournera toujours la bonne icône, à la bonne taille et en PNG.

Ça m’est venu pour les blogs de Tumblr, de la form _blog.tumblr.com_, qui n’ont pas de favicon à la racine, mais qui en ont une dans le HTML (et dans des tailles bizarres).
Exemple, ce blog : http://cuteness--overload.tumblr.com/
Sa favicon dans les fichiers est http://33.media.tumblr.com/avatar_e08c00fa4002_128.png

Ton idée est bonne, mais je pense qu’il faut faire un projet à part. Genre un _favicon-finder_ ou un truc comme ça. Ce projet fournirait une API similaire au truc de Google ou de Gravatar et on pourra ensuite implémenter cet API dans **local-favicon-cache**.

C’est bien plus de travail : il faut détecter des choses comme : 
- format du fichier,
- taille de l’image,
- recherche de l’icône:
 * à la racine du site
 * dans les entêtes,
 * dans le code ; avec la gestion merdique lié à ça :
   * encodage,
    * code html non conforme ou exotique,
    * code compressé GZip,
    * retour 403 à cause du referer/cookies/user-agent non reconnus…
* prise en charge de cloudflare et autres captcha (par exemple Youtube inaccessible depuis les IP d’OVH)

Ce n’est pas impossible à faire mais c’est un foutoir.


Alternativement il y a aussi ces services :
- http://grabicon.com/
- http://www.faviconfinder.com/
- http://www.faviconfinder.tk/
- https://icons.better-idea.org
- http://seositecheckup.com/tools/favicon-test
